"""Render per-category comparison matrices into ``docs/*-matrix.md``.

Reads the curated YAML under ``registry/<category>/`` and the metadata
sidecars under ``registry/_metadata/`` (if present), and writes one Markdown
table per category. Tables show capability axes, not rankings — per
``GOVERNANCE.md`` §4 the atlas is explicitly not a leaderboard.

Usage:
    python scripts/build_matrices.py            # write matrices
    python scripts/build_matrices.py --check    # exit 1 on drift (CI gate)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_DIR = REPO_ROOT / "registry"
METADATA_DIR = REGISTRY_DIR / "_metadata"
DOCS_DIR = REPO_ROOT / "docs"

CATEGORIES = ["governance", "agent", "eval", "redteam", "routing", "education"]
HEADER_NOTE = (
    "<!-- AUTO-GENERATED by scripts/build_matrices.py — do not hand-edit. "
    "Edit the per-entry YAML under registry/<category>/ and re-run. -->"
)


def _load_entries(category: str) -> list[dict[str, Any]]:
    folder = REGISTRY_DIR / category
    entries: list[dict[str, Any]] = []
    if not folder.is_dir():
        return entries
    for path in sorted(folder.glob("*.yaml")):
        if path.name.startswith("_"):
            continue
        with path.open(encoding="utf-8") as fh:
            data = yaml.safe_load(fh) or {}
        sidecar = METADATA_DIR / f"{data.get('id', path.stem)}.json"
        if sidecar.exists():
            with sidecar.open(encoding="utf-8") as fh:
                data["_sidecar"] = json.load(fh)
        entries.append(data)
    return entries


def _md_escape(text: str | None) -> str:
    if text is None:
        return ""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _stars_cell(entry: dict[str, Any]) -> str:
    sidecar = entry.get("_sidecar")
    if not sidecar or sidecar.get("stars") is None:
        return "—"
    stars = sidecar["stars"]
    if stars >= 1000:
        return f"{stars / 1000:.1f}k"
    return str(stars)


def _link_name(entry: dict[str, Any]) -> str:
    return f"[{_md_escape(entry.get('name'))}]({entry.get('repo_url', '')})"


def _agnostic_cell(entry: dict[str, Any]) -> str:
    score = entry.get("model_agnostic_score")
    if score is None:
        return "—"
    return f"{score}/5"


def _render_common(category: str, entries: list[dict[str, Any]]) -> str:
    title = {
        "governance": "Governance harnesses",
        "agent": "Agent frameworks",
        "eval": "Evaluation harnesses",
        "redteam": "Red-team / safety harnesses",
        "routing": "Routing / model-agnostic infrastructure",
        "education": "Free education resources",
    }[category]
    lines: list[str] = []
    lines.append(HEADER_NOTE)
    lines.append("")
    lines.append(f"# {title} — comparison matrix")
    lines.append("")
    lines.append(
        "This matrix shows capability axes per entry; it is **not** a ranking "
        "or leaderboard (see `GOVERNANCE.md` §4). "
        "Read each entry's curated `sovereignty_notes` for the qualitative "
        "context behind every score."
    )
    lines.append("")
    return "\n".join(lines)


def _render_default(category: str, entries: list[dict[str, Any]]) -> str:
    parts = [_render_common(category, entries)]
    parts.append(
        "| Entry | License | Lang | Maturity | Origin | Model-agnostic | Stars | Maintainer |"
    )
    parts.append(
        "|---|---|---|---|---|---|---|---|"
    )
    for entry in entries:
        parts.append(
            "| {name} | {license} | {lang} | {maturity} | {origin} | {agn} | {stars} | {maint} |".format(
                name=_link_name(entry),
                license=_md_escape(entry.get("license")),
                lang=_md_escape(entry.get("primary_language")),
                maturity=_md_escape(entry.get("maturity")),
                origin=_md_escape(entry.get("origin_country") or "—"),
                agn=_agnostic_cell(entry),
                stars=_stars_cell(entry),
                maint=_md_escape((entry.get("maintainer") or {}).get("name")),
            )
        )
    parts.append("")
    parts.append(
        f"_Generated from `registry/{category}/*.yaml` (+ `registry/_metadata/*.json` if present). "
        "Run `python scripts/build_matrices.py` to refresh._"
    )
    parts.append("")
    return "\n".join(parts)


def _render_governance(entries: list[dict[str, Any]]) -> str:
    parts = [_render_common("governance", entries)]
    parts.append(
        "| Entry | License | Lang | Policy router | Source authority | "
        "Prompt composer | Output contract | Audit-log FSM | Agnostic |"
    )
    parts.append(
        "|---|---|---|---|---|---|---|---|---|"
    )
    for entry in entries:
        cov = entry.get("five_component_coverage") or {}
        parts.append(
            "| {name} | {lic} | {lang} | {pr} | {sa} | {pc} | {oc} | {al} | {agn} |".format(
                name=_link_name(entry),
                lic=_md_escape(entry.get("license")),
                lang=_md_escape(entry.get("primary_language")),
                pr=_md_escape(cov.get("policy_router") or "—"),
                sa=_md_escape(cov.get("source_authority") or "—"),
                pc=_md_escape(cov.get("prompt_composer") or "—"),
                oc=_md_escape(cov.get("output_contract") or "—"),
                al=_md_escape(cov.get("audit_log_fsm") or "—"),
                agn=_agnostic_cell(entry),
            )
        )
    parts.append("")
    parts.append(
        "Component coverage values: `native` | `aligned` | `partial` | `none`. "
        "Definitions in `docs/five-component-overlay.md`."
    )
    parts.append("")
    return "\n".join(parts)


def _render_education(entries: list[dict[str, Any]]) -> str:
    parts = [_render_common("education", entries)]
    parts.append("| Entry | License | Maintainer | Origin | Resources |")
    parts.append("|---|---|---|---|---|")
    for entry in entries:
        resources = entry.get("education_resources") or []
        resource_links = "; ".join(
            f"[{_md_escape(r.get('title'))}]({r.get('url', '')})" for r in resources
        ) or "—"
        parts.append(
            "| {name} | {lic} | {maint} | {origin} | {res} |".format(
                name=_link_name(entry),
                lic=_md_escape(entry.get("license")),
                maint=_md_escape((entry.get("maintainer") or {}).get("name")),
                origin=_md_escape(entry.get("origin_country") or "—"),
                res=resource_links,
            )
        )
    parts.append("")
    return "\n".join(parts)


RENDERERS = {
    "governance": _render_governance,
    "education": _render_education,
}


def _render_category(category: str) -> str:
    entries = _load_entries(category)
    renderer = RENDERERS.get(category, lambda es: _render_default(category, es))
    return renderer(entries)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if the matrices on disk differ from the freshly rendered output.")
    args = parser.parse_args(argv)

    drift = False
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    for category in CATEGORIES:
        rendered = _render_category(category) + "\n"
        out_path = DOCS_DIR / f"{category}-matrix.md"
        if args.check:
            existing = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
            if existing != rendered:
                sys.stderr.write(f"DRIFT: {out_path.relative_to(REPO_ROOT)}\n")
                drift = True
        else:
            out_path.write_text(rendered, encoding="utf-8")
            print(f"wrote {out_path.relative_to(REPO_ROOT)}")
    return 1 if drift else 0


if __name__ == "__main__":
    raise SystemExit(main())
